# 服务端口
server:
  port: 8005

# 服务名
spring:
  application:
    name: edu-cms

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database:  0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        min-idle: 0
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:cn/blue/educms/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl