# 服务端口
server:
  port: 8002
## 服务名
spring:
  application:
    name: service-edu

  # 环境设置：dev、test、prod
  profiles:
    active: dev

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  # 配置扫描xml
  mapper-locations: classpath:/cn/blue/eduservice/mapper/**/*.xml

# 开启熔断机制
feign:
  hystrix:
    enabled: true
# 设置hystrix超时时间,默认1000ms
# 设置hystrix超时时间，默认1000ms
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=6000